name: Update Heroku Link on Fork

on:
  fork:
    types: [created]

jobs:
  update-link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          USERNAME=$(echo "${{ github.actor }}")
          NEW_LINK="https://dashboard.heroku.com/new?template=https://github.com/$USERNAME/ChatBot"
          sed -i "s|https://dashboard.heroku.com/new?template=https://github.com/TheChampu/ChatBot|$NEW_LINK|g" README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update Heroku deployment link for forked repository"
          git push